config/routes.rb
# == Route Map
#
#                 Prefix Verb   URI Pattern                       Controller#Action
#                   root GET    /                                 static_pages#home
#               patients GET    /patients(.:format)               patients#index
#                        POST   /patients(.:format)               patients#create
#            new_patient GET    /patients/new(.:format)           patients#new
#           edit_patient GET    /patients/:id/edit(.:format)      patients#edit
#                patient GET    /patients/:id(.:format)           patients#show
#                        PATCH  /patients/:id(.:format)           patients#update
#                        PUT    /patients/:id(.:format)           patients#update
#                        DELETE /patients/:id(.:format)           patients#destroy
#       patient_sessions POST   /patient_sessions(.:format)       patient_sessions#create
#   new_patient_sessions GET    /patient_sessions/new(.:format)   patient_sessions#new
#                        DELETE /patient_sessions(.:format)       patient_sessions#destroy
#      basic_info_doctor GET    /doctors/:id/basic_info(.:format) doctors#basic_info
#                        POST   /doctors/:id/basic_info(.:format) doctors#update_basic_info
#         search_doctors GET    /doctors/search(.:format)         doctor_search#index
#                doctors GET    /doctors(.:format)                doctors#index
#                        POST   /doctors(.:format)                doctors#create
#             new_doctor GET    /doctors/new(.:format)            doctors#new
#            edit_doctor GET    /doctors/:id/edit(.:format)       doctors#edit
#                 doctor GET    /doctors/:id(.:format)            doctors#show
#                        PATCH  /doctors/:id(.:format)            doctors#update
#                        PUT    /doctors/:id(.:format)            doctors#update
#                        DELETE /doctors/:id(.:format)            doctors#destroy
#        doctor_sessions POST   /doctor_sessions(.:format)        doctor_sessions#create
#    new_doctor_sessions GET    /doctor_sessions/new(.:format)    doctor_sessions#new
#                        DELETE /doctor_sessions(.:format)        doctor_sessions#destroy
#                 admins GET    /admins(.:format)                 admins#index
#                        POST   /admins(.:format)                 admins#create
#              new_admin GET    /admins/new(.:format)             admins#new
#             edit_admin GET    /admins/:id/edit(.:format)        admins#edit
#                  admin GET    /admins/:id(.:format)             admins#show
#                        PATCH  /admins/:id(.:format)             admins#update
#                        PUT    /admins/:id(.:format)             admins#update
#                        DELETE /admins/:id(.:format)             admins#destroy
#         admin_sessions POST   /admin_sessions(.:format)         admin_sessions#create
#     new_admin_sessions GET    /admin_sessions/new(.:format)     admin_sessions#new
#                        DELETE /admin_sessions(.:format)         admin_sessions#destroy
#           specialities GET    /specialities(.:format)           specialities#index
#                        POST   /specialities(.:format)           specialities#create
#         new_speciality GET    /specialities/new(.:format)       specialities#new
#        edit_speciality GET    /specialities/:id/edit(.:format)  specialities#edit
#             speciality GET    /specialities/:id(.:format)       specialities#show
#                        PATCH  /specialities/:id(.:format)       specialities#update
#                        PUT    /specialities/:id(.:format)       specialities#update
#                        DELETE /specialities/:id(.:format)       specialities#destroy
#              hospitals GET    /hospitals(.:format)              hospitals#index
#                        POST   /hospitals(.:format)              hospitals#create
#           new_hospital GET    /hospitals/new(.:format)          hospitals#new
#          edit_hospital GET    /hospitals/:id/edit(.:format)     hospitals#edit
#               hospital GET    /hospitals/:id(.:format)          hospitals#show
#                        PATCH  /hospitals/:id(.:format)          hospitals#update
#                        PUT    /hospitals/:id(.:format)          hospitals#update
#                        DELETE /hospitals/:id(.:format)          hospitals#destroy
# search_cities_by_state POST   /search/cities_by_state(.:format) doctor_search#cities_by_state
#

Rails.application.routes.draw do

  root 'static_pages#home'

  resources :patients
  resource :patient_sessions, only: [:new, :create, :destroy]

  resources :doctors do
    member do
      get 'basic_info'
      post 'basic_info', to: 'doctors#update_basic_info'
    end

    collection do
      get 'search', to: 'doctor_search#index'
    end
  end
  resource :doctor_sessions, only: [:new, :create, :destroy]

  resources :admins
  resource :admin_sessions, only: [:new, :create, :destroy]

  resources :specialities
  resources :hospitals

  post 'search/cities_by_state', to: "doctor_search#cities_by_state"

end

app/models/speciality.rb
# == Schema Information
#
# Table name: specialities
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Speciality < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

end

app/controllers/specialities_controller.rb
class SpecialitiesController < ApplicationController

  def index
    @specialities = Speciality.all.order(:name).page(params[:page])
  end

  def show
    @speciality = Speciality.find(params[:id])
  end

  def new
    @speciality = Speciality.new
  end

  def create
    @speciality = Speciality.new(speciality_params)
    if @speciality.save
      flash[:success] = "New Speciality Added"
      redirect_to specialities_path
    else
      render:new
    end
  end

  def edit
    @speciality = Speciality.find(params[:id])
  end

  def update
    @speciality = Speciality.find(params[:id])
    if @speciality.update(speciality_params)
      flash[:success] = "Speciality Updated"
      redirect_to specialities_path
    else
      render :edit
    end
  end

  def destroy
    @speciality = Speciality.find(params[:id])
    @speciality.destroy
    flash[:success] = "Speciality has been deleted"
    redirect_to specialities_path
  end

  private

    def speciality_params
      params.require(:speciality).permit(:name)
    end

end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/views/specialities/edit.html.erb
<div class="container">

  <h2 class="text-center col-sm-7">Edit Speciality <%= @speciality.name %></h2>
  <div class="clearfix"></div>
  <%= simple_form_for @speciality, html: { class: 'form-horizontal' }, wrapper: :horizontal_input_group do |f| %>

    <div class="form-inputs">
      <%= f.input :name, required: false %>

      <div class="form-actions col-sm-offset-2">
        <%= f.button :submit, "Update", class: 'btn-lg' %>
      </div>

    </div>
  <% end %>

  <p class="col-sm-offset-2 index-link"><%= link_to "All Specialities", specialities_path %></p>
</div>

app/views/specialities/index.html.erb
<div class="container">
  <div class="table-responsive">
    <table class="table table-hover table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @specialities.each do |speciality| %>
        <tr>
          <td><%= link_to speciality.name, speciality_path(speciality) %></td>
          <td><%= link_to("Edit", edit_speciality_path(speciality)) %></td>
          <td><%= link_to("Delete", speciality_path(speciality), method: :delete) %></td>
        </tr>
      <% end %>
    </tbody>
    </table>
  </div>

  <p><%= link_to "New Speciality", new_speciality_path %></p>
  <%= will_paginate @specialities %>
</div>

app/views/specialities/new.html.erb
<div class="container">

  <h2 class="text-center col-sm-7">New Speciality</h2>
  <div class="clearfix"></div>
  <%= simple_form_for @speciality, html: { class: 'form-horizontal' }, wrapper: :horizontal_input_group do |f| %>

    <div class="form-inputs">
      <%= f.input :name, required: false %>

      <div class="form-actions col-sm-offset-2">
        <%= f.button :submit, "Create", class: 'btn-lg' %>
      </div>

    </div>
  <% end %>

  <p class="col-sm-offset-2 index-link"><%= link_to "All Specialities", specialities_path %></p>
</div>

app/views/specialities/show.html.erb
<div class="container">
  <p>This page will contain more info about speciality: <%= @speciality.name %></p>

  <p><%= link_to "All Specialities", specialities_path %></p>
</div>