config/routes.rb
# == Route Map
#
#                 Prefix Verb   URI Pattern                       Controller#Action
#                   root GET    /                                 static_pages#home
#               patients GET    /patients(.:format)               patients#index
#                        POST   /patients(.:format)               patients#create
#            new_patient GET    /patients/new(.:format)           patients#new
#           edit_patient GET    /patients/:id/edit(.:format)      patients#edit
#                patient GET    /patients/:id(.:format)           patients#show
#                        PATCH  /patients/:id(.:format)           patients#update
#                        PUT    /patients/:id(.:format)           patients#update
#                        DELETE /patients/:id(.:format)           patients#destroy
#       patient_sessions POST   /patient_sessions(.:format)       patient_sessions#create
#   new_patient_sessions GET    /patient_sessions/new(.:format)   patient_sessions#new
#                        DELETE /patient_sessions(.:format)       patient_sessions#destroy
#      basic_info_doctor GET    /doctors/:id/basic_info(.:format) doctors#basic_info
#                        POST   /doctors/:id/basic_info(.:format) doctors#update_basic_info
#         search_doctors GET    /doctors/search(.:format)         doctor_search#index
#                doctors GET    /doctors(.:format)                doctors#index
#                        POST   /doctors(.:format)                doctors#create
#             new_doctor GET    /doctors/new(.:format)            doctors#new
#            edit_doctor GET    /doctors/:id/edit(.:format)       doctors#edit
#                 doctor GET    /doctors/:id(.:format)            doctors#show
#                        PATCH  /doctors/:id(.:format)            doctors#update
#                        PUT    /doctors/:id(.:format)            doctors#update
#                        DELETE /doctors/:id(.:format)            doctors#destroy
#        doctor_sessions POST   /doctor_sessions(.:format)        doctor_sessions#create
#    new_doctor_sessions GET    /doctor_sessions/new(.:format)    doctor_sessions#new
#                        DELETE /doctor_sessions(.:format)        doctor_sessions#destroy
#                 admins GET    /admins(.:format)                 admins#index
#                        POST   /admins(.:format)                 admins#create
#              new_admin GET    /admins/new(.:format)             admins#new
#             edit_admin GET    /admins/:id/edit(.:format)        admins#edit
#                  admin GET    /admins/:id(.:format)             admins#show
#                        PATCH  /admins/:id(.:format)             admins#update
#                        PUT    /admins/:id(.:format)             admins#update
#                        DELETE /admins/:id(.:format)             admins#destroy
#         admin_sessions POST   /admin_sessions(.:format)         admin_sessions#create
#     new_admin_sessions GET    /admin_sessions/new(.:format)     admin_sessions#new
#                        DELETE /admin_sessions(.:format)         admin_sessions#destroy
#           specialities GET    /specialities(.:format)           specialities#index
#                        POST   /specialities(.:format)           specialities#create
#         new_speciality GET    /specialities/new(.:format)       specialities#new
#        edit_speciality GET    /specialities/:id/edit(.:format)  specialities#edit
#             speciality GET    /specialities/:id(.:format)       specialities#show
#                        PATCH  /specialities/:id(.:format)       specialities#update
#                        PUT    /specialities/:id(.:format)       specialities#update
#                        DELETE /specialities/:id(.:format)       specialities#destroy
#              hospitals GET    /hospitals(.:format)              hospitals#index
#                        POST   /hospitals(.:format)              hospitals#create
#           new_hospital GET    /hospitals/new(.:format)          hospitals#new
#          edit_hospital GET    /hospitals/:id/edit(.:format)     hospitals#edit
#               hospital GET    /hospitals/:id(.:format)          hospitals#show
#                        PATCH  /hospitals/:id(.:format)          hospitals#update
#                        PUT    /hospitals/:id(.:format)          hospitals#update
#                        DELETE /hospitals/:id(.:format)          hospitals#destroy
# search_cities_by_state POST   /search/cities_by_state(.:format) doctor_search#cities_by_state
#

Rails.application.routes.draw do

  root 'static_pages#home'

  resources :patients
  resource :patient_sessions, only: [:new, :create, :destroy]

  resources :doctors do
    member do
      get 'basic_info'
      post 'basic_info', to: 'doctors#update_basic_info'
    end

    collection do
      get 'search', to: 'doctor_search#index'
    end
  end
  resource :doctor_sessions, only: [:new, :create, :destroy]

  resources :admins
  resource :admin_sessions, only: [:new, :create, :destroy]

  resources :specialities
  resources :hospitals

  post 'search/cities_by_state', to: "doctor_search#cities_by_state"

end

app/views/layouts/navbars/_admin_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>>
        PFI
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href=<%= root_path %>>Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">About</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Patients Portal <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="">All Patients</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Doctors Portal <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="">All Doctors</a></li>
            <li role="separator" class="divider"></li>
            <li><a href=<%= hospitals_path %>>All Hospitals</a></li>
            <li role="separator" class="divider"></li>
            <li><a href=<%= specialities_path %>>All Specialities</a></li>
          </ul>
        </li>
        <li><%= link_to "Log Out", admin_sessions_path, method: :delete %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Contact Us</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/navbars/_doctor_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>>
        PFI
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href=<%= root_path %>>Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">About</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Data <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="">Past Checkups</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_doctor.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href=<%= basic_info_doctor_path(current_doctor) %>>Basic Info</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log Out", doctor_sessions_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Contact Us</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/navbars/_not_logged_in_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>>
        PFI
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href=<%= root_path %>>Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">About</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Patients <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href=<%= new_patient_sessions_path %>>Log In</a></li>
            <li role="separator" class="divider"></li>
            <li><a href=<%= new_patient_path %>>Sign Up</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Doctors <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href=<%= new_doctor_sessions_path %>>Log In</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Contact Us</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/navbars/_patient_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>>
        PFI
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href=<%= root_path %>>Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">About</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Data <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="">Checkups</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="">Reports</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="">Alerts</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_patient.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="">Basic Details</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="">Approved Doctors</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log Out", patient_sessions_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Contact Us</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>