config/routes.rb
# == Route Map
#
#                 Prefix Verb   URI Pattern                       Controller#Action
#                   root GET    /                                 static_pages#home
#               patients GET    /patients(.:format)               patients#index
#                        POST   /patients(.:format)               patients#create
#            new_patient GET    /patients/new(.:format)           patients#new
#           edit_patient GET    /patients/:id/edit(.:format)      patients#edit
#                patient GET    /patients/:id(.:format)           patients#show
#                        PATCH  /patients/:id(.:format)           patients#update
#                        PUT    /patients/:id(.:format)           patients#update
#                        DELETE /patients/:id(.:format)           patients#destroy
#       patient_sessions POST   /patient_sessions(.:format)       patient_sessions#create
#   new_patient_sessions GET    /patient_sessions/new(.:format)   patient_sessions#new
#                        DELETE /patient_sessions(.:format)       patient_sessions#destroy
#      basic_info_doctor GET    /doctors/:id/basic_info(.:format) doctors#basic_info
#                        POST   /doctors/:id/basic_info(.:format) doctors#update_basic_info
#         search_doctors GET    /doctors/search(.:format)         doctor_search#index
#                doctors GET    /doctors(.:format)                doctors#index
#                        POST   /doctors(.:format)                doctors#create
#             new_doctor GET    /doctors/new(.:format)            doctors#new
#            edit_doctor GET    /doctors/:id/edit(.:format)       doctors#edit
#                 doctor GET    /doctors/:id(.:format)            doctors#show
#                        PATCH  /doctors/:id(.:format)            doctors#update
#                        PUT    /doctors/:id(.:format)            doctors#update
#                        DELETE /doctors/:id(.:format)            doctors#destroy
#        doctor_sessions POST   /doctor_sessions(.:format)        doctor_sessions#create
#    new_doctor_sessions GET    /doctor_sessions/new(.:format)    doctor_sessions#new
#                        DELETE /doctor_sessions(.:format)        doctor_sessions#destroy
#                 admins GET    /admins(.:format)                 admins#index
#                        POST   /admins(.:format)                 admins#create
#              new_admin GET    /admins/new(.:format)             admins#new
#             edit_admin GET    /admins/:id/edit(.:format)        admins#edit
#                  admin GET    /admins/:id(.:format)             admins#show
#                        PATCH  /admins/:id(.:format)             admins#update
#                        PUT    /admins/:id(.:format)             admins#update
#                        DELETE /admins/:id(.:format)             admins#destroy
#         admin_sessions POST   /admin_sessions(.:format)         admin_sessions#create
#     new_admin_sessions GET    /admin_sessions/new(.:format)     admin_sessions#new
#                        DELETE /admin_sessions(.:format)         admin_sessions#destroy
#           specialities GET    /specialities(.:format)           specialities#index
#                        POST   /specialities(.:format)           specialities#create
#         new_speciality GET    /specialities/new(.:format)       specialities#new
#        edit_speciality GET    /specialities/:id/edit(.:format)  specialities#edit
#             speciality GET    /specialities/:id(.:format)       specialities#show
#                        PATCH  /specialities/:id(.:format)       specialities#update
#                        PUT    /specialities/:id(.:format)       specialities#update
#                        DELETE /specialities/:id(.:format)       specialities#destroy
#              hospitals GET    /hospitals(.:format)              hospitals#index
#                        POST   /hospitals(.:format)              hospitals#create
#           new_hospital GET    /hospitals/new(.:format)          hospitals#new
#          edit_hospital GET    /hospitals/:id/edit(.:format)     hospitals#edit
#               hospital GET    /hospitals/:id(.:format)          hospitals#show
#                        PATCH  /hospitals/:id(.:format)          hospitals#update
#                        PUT    /hospitals/:id(.:format)          hospitals#update
#                        DELETE /hospitals/:id(.:format)          hospitals#destroy
# search_cities_by_state POST   /search/cities_by_state(.:format) doctor_search#cities_by_state
#

Rails.application.routes.draw do

  root 'static_pages#home'

  resources :patients
  resource :patient_sessions, only: [:new, :create, :destroy]

  resources :doctors do
    member do
      get 'basic_info'
      post 'basic_info', to: 'doctors#update_basic_info'
    end

    collection do
      get 'search', to: 'doctor_search#index'
    end
  end
  resource :doctor_sessions, only: [:new, :create, :destroy]

  resources :admins
  resource :admin_sessions, only: [:new, :create, :destroy]

  resources :specialities
  resources :hospitals

  post 'search/cities_by_state', to: "doctor_search#cities_by_state"

end

app/models/hospital.rb
# == Schema Information
#
# Table name: hospitals
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Hospital < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true
  validates_associated :address, presence: true

  has_many :doctor_hospitals, dependent: :destroy
  has_many :doctors, through: :doctor_hospitals
  has_one :address, as: :addressable, dependent: :destroy

  accepts_nested_attributes_for :address

end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController

  def index
    @hospitals = Hospital.includes(:address).all.order(:name).page(params[:page])
  end

  def show
    @hospital = Hospital.find(params[:id])
  end

  def new
    @hospital = Hospital.new
    @address = @hospital.build_address
  end

  def create
    @hospital = Hospital.new(hospital_params)
    if @hospital.save
      flash[:success] = "New Hospital Added"
      redirect_to hospitals_path
    else
      render:new
    end
  end

  def edit
    @hospital = Hospital.find(params[:id])
  end

  def update
    @hospital = Hospital.find(params[:id])
    if @hospital.update(hospital_params)
      flash[:success] = "Hospital Updated"
      redirect_to hospitals_path
    else
      render :edit
    end
  end

  def destroy
    @hospital = Hospital.find(params[:id])
    @hospital.destroy
    flash[:success] = "Hospital has been deleted"
    redirect_to hospitals_path
  end

  private

    def hospital_params
      params.require(:hospital).permit(:name, address_attributes: [:state, :city, :pincode, :address_lines])
    end

end

app/views/hospitals/edit.html.erb
<div class="container">

  <h2 class="text-center col-sm-7">Edit Hospital</h2>
  <div class="clearfix"></div>
  <%= simple_form_for @hospital, html: { class: 'form-horizontal' }, wrapper: :horizontal_input_group do |f| %>

    <div class="form-inputs">
      <%= f.input :name, required: false %>

      <%= f.simple_fields_for(:address, wrapper: :horizontal_input_group) do |ff| %>
        <%= ff.input :state, collection: Address::INDIAN_STATES, required: false %>
        <%= ff.input :city, required: false %>
        <%= ff.input :pincode, required: false %>
        <%= ff.input :address_lines, required: false, as: :text %>
      <% end %>

      <div class="form-actions col-sm-offset-2">
        <%= f.button :submit, "Update", class: 'btn-lg' %>
      </div>

    </div>
  <% end %>

  <p class="col-sm-offset-2 index-link"><%= link_to "All Hospitals", hospitals_path %></p>
</div>

app/views/hospitals/index.html.erb
<div class="container">
  <div class="table-responsive">
    <table class="table table-hover table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Location</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @hospitals.each do |hospital| %>
        <tr>
          <td><%= link_to hospital.name, hospital_path(hospital) %></td>
          <td><%= hospital.address.city + ", " + hospital.address.state %></td>
          <td><%= link_to("Edit", edit_hospital_path(hospital)) %></td>
          <td><%= link_to("Delete", hospital_path(hospital), method: :delete) %></td>
        </tr>
      <% end %>
    </tbody>
    </table>
  </div>

  <p><%= link_to "New Hospital", new_hospital_path %></p>
  <%= will_paginate @hospitals %>
</div>

app/views/hospitals/new.html.erb
<div class="container">

  <h2 class="text-center col-sm-7">New Hospital</h2>
  <div class="clearfix"></div>
  <%= simple_form_for @hospital, html: { class: 'form-horizontal' }, wrapper: :horizontal_input_group do |f| %>

    <div class="form-inputs">
      <%= f.input :name, required: false %>

      <%= f.simple_fields_for(:address, wrapper: :horizontal_input_group) do |ff| %>
        <%= ff.input :state, collection: Address::INDIAN_STATES, required: false %>
        <%= ff.input :city, required: false %>
        <%= ff.input :pincode, required: false %>
        <%= ff.input :address_lines, required: false, as: :text %>
      <% end %>

      <div class="form-actions col-sm-offset-2">
        <%= f.button :submit, "Create", class: 'btn-lg' %>
      </div>

    </div>
  <% end %>

  <p class="col-sm-offset-2 index-link"><%= link_to "All Hospitals", hospitals_path %></p>
</div>

app/views/hospitals/show.html.erb
<div class="container">
  <p>This page will contain more info about hospital: <%= @hospital.name %></p>

  <p><%= link_to "All Hospitals", hospitals_path %></p>
</div>